parameters:
#    de_wei_website.example.class: deWei\WebsiteBundle\Example

services:
#    de_wei_website.example:
#        class: %de_wei_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
